### PR TITLE
Adjust the template check for the Certificate template preview

### LINKED ISSUE #361: Certificate template not previewing if there's no single.php template
### Steps to Reproduce
1. Activate a theme without a `single.php` template
2. Create a certificate template
3. Preview it 

### What I Expected
A PDF should be rendered as a preview.

### What Happened Instead
The certificate template is rendered using a default page template.

### PHP / WordPress / Sensei Certificates / Sensei LMS version
-WooCommerce: 9.3.3
- Sensei LMS:  4.24.3
- Sensei Certificates: 2.5.2

### PR DESCRIPTION
**Pull request by bernattorras**
### Changes proposed in this Pull Request

* Adjust the template check for the Certificate template preview to make sure that the preview template is used even if the current theme doesn't have any `single.php` template

### Description

By default, the plugin checks if `strpos( $locate, 'single.php' )` to confirm if the current page corresponds to a single certificate template page, but `$locate` is an empty string if the current theme doesn't have a `single.php` template, forcing the page to get rendered using the default page template. 

I suggest checking the `$type` parameter that is passed by the filter to check if it's a single template instead. 

### Testing instructions

* Activate a theme without a single.php template
* Create a certificate template
* Preview it
* Confirm that a PDF preview is rendered instead of using a default page template.

Mentions #361

### CODE REVIEW

File: classes/class-woothemes-sensei-certificate-templates.php [hunk 1]
```diff
@@ -193,16 +193,15 @@ public function plugin_path() {
 	 * @param string $locate locate path
 	 * @return string the location path for the certificate template preview file
 	 */
-	function certificate_templates_locate_preview_template( $locate ) {
+	public function certificate_templates_locate_preview_template( $locate, $type, $templates ) {
```
Comment (donnapep) [inline classes/class-woothemes-sensei-certificate-templates.php]: Thanks for the PR @bernattorras. Would you mind updating the comment for this function to include the additional params that are now being passed? 🙇🏻‍♀️

Comment (donnapep) [reply classes/class-woothemes-sensei-certificate-templates.php]: Also, since we're not using `$templates`, maybe we can skip passing it?

**Comment by bernattorras** [comment]
Thanks for reviewing it @donnapep! 

I've updated the code as per your comments. 👍

**Review by donnapep — APPROVED** [review]
