### PR TITLE
Fix missing "View Certificate" link in `sensei_user_courses` shortcode

### LINKED ISSUE #347: No "View Certificate" link displayed on page containing `sensei_user_courses` shortcode
### Steps to Reproduce
1. Attach a certificate to a course.
2. Complete the course as a student.
3. Add the `[sensei_user_courses]` shortcode to a page.
4. View that page as the student who completed the course.

### What I Expected
To see a _View Certificate_ link as you do in Sensei Certificates 2.4.0.

### What Happened Instead
No _View Certificate_ link appears on the My Courses page.

This was likely caused by https://github.com/woocommerce/sensei-certificates/pull/341.

### PHP / WordPress / Sensei Certificates / Sensei LMS version
Sensei Certificates 2.4.0
Sensei LMS 4.16.1

#### Sensei Certificates 2.4.0
Screenshot 2023-09-12 at 12 17 04 PM

#### Sensei Certificates 2.5.0
Screenshot 2023-09-12 at 12 17 40 PM

### Context / Source
6793270-zen

### PR DESCRIPTION
**Pull request by donnapep**
Fixes #347.

### Changes proposed in this Pull Request
Reverts [changes to the `if` condition](https://github.com/woocommerce/sensei-certificates/pull/341/files#diff-79049456e2b059cbdcd7080ec2f30f2b3a347b4c41746fd452a68d7be711ac26R1082) made in #341. In particular, the `is_page( $my_account_page_id )` is not equivalent to `'page' == get_post_type( $my_account_page_id )` on the legacy My Courses page, as `is_page` returns `false` for archive pages.

### Testing instructions
1. Attach a certificate to a course.
2. Complete the course as a student.
3. Add the `[sensei_user_courses]` shortcode to a page.
4. View that page as the student who completed the course.
5. Ensure the _View Certificate_ link is visible for that course and that it works.
6. In WP Admin, navigate to _Sensei LMS > Settings > Student Profiles_ and ensure _Public student profiles_ is checked.
7. In WP Admin, navigate to _Sensei LMS > Settings > Certificate Settings_ and ensure _Public Certificate_ is checked.
8. Ensure that there is a user who has completed at least one course that has a certificate.
9. As that user, navigate to their Learner profile (`<site-url>/learner/<login>`) and check `Allow my Certificates to be publicly viewed`. Save the setting.
10. Navigate to the _Completed Courses_ tab. Ensure the "View Certificate" button is visible.
11. Open the user's Learner profile in an incognito/private window.
12. Navigate to the _Completed Courses_ tab. Ensure the "View Certificate" button is visible.

### Screenshot / Video
Screenshot 2023-09-13 at 10 51 56 AM

### CODE REVIEW

File: classes/class-woothemes-sensei-certificates.php [hunk 1]
```diff
@@ -1084,43 +1084,28 @@ public function certificate_link( $message, $course_id = 0, $user_id = 0 ) {
...
-					|| is_singular( 'course' )
-					|| isset( $wp_query->query_vars['course_results'] )
-				)
-				&& $view_link_courses
-			) || (
-				isset( $wp_query->query_vars['learner_profile'] )
-				&& $view_link_profile
-			)
-		) {
+		if ( ( 'page' == get_post_type( $my_account_page_id )
```
Comment (merkushin) [inline classes/class-woothemes-sensei-certificates.php]: Maybe leave a comment about the difference between these checks?

**Review by merkushin — DISMISSED** [review]
Works as described 👍

File: classes/class-woothemes-sensei-certificates.php (hunk 1 above)
Comment (donnapep) [reply classes/class-woothemes-sensei-certificates.php]: Updated in https://github.com/woocommerce/sensei-certificates/pull/348/commits/0f6b5b7a18b3bd7739e00e03984e6ba99162b69c.

**Review by merkushin — APPROVED** [review]

File: classes/class-woothemes-sensei-certificates.php (hunk 1 above)
Comment (merkushin) [reply classes/class-woothemes-sensei-certificates.php]: Sorry, my comment was a bit vague. 
I was thinking more about the difference between `is_page( ... )` and `'page' === get_post_type( ... )` to prevent similar changes in the future.

**Review by GeoJunkie — APPROVED** [review]
Tested on the site we implemented #341 for, and everything still works properly. No concerns here.

File: classes/class-woothemes-sensei-certificates.php (hunk 1 above)
Comment (donnapep) [reply classes/class-woothemes-sensei-certificates.php]: I decided not to put that in since a Google search will give you the answer. 🙂
